trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: DeployD
  displayName: Dev Deployment
steps:
  - task: FileTransform@1
    inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/**/*.zip'
    fileType: 'json'