trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: DeployD
  displayName: Dev Deployment

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"

steps:
  - task: FileTransform@1
    inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/**/*.zip'
    fileType: 'json'