trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: DeployD
  displayName: Dev Deployment

jobs:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"